### ISSUE TITLE
Add support for parsing from memory

### ISSUE THREAD

**Issue by cpendery** [bigkevmcd/go-configparser#13]
It would be great if you could expose add a public interface like the `Parse` method below, but instead of taking in a filename it takes in a `[]byte` or a `io.Reader` so parsing can be done with data in memory rather than on disk https://github.com/bigkevmcd/go-configparser/blob/50bee8f8db3677122af3acf177a09e6ed8688797/configparser.go#L144

**Comment by bigkevmcd** [comment]
I exposed `ParseReader` in the code.

This is really old code, there are some thing that can definitely be better in there :-)
