### ISSUE TITLE
When there are square brackets in the value, it is misparsed into a section

### ISSUE THREAD

**Issue by aprodigalson** [bigkevmcd/go-configparser#18]
Problem:
When there are square brackets in the value, it is misparsed into a section

Input:

[section]
option1 = prefix[teststring]suffix

For the above example parser.Sections() returns [section, teststring].

Expected:
For the above example parser.Sections() should return [section].

**Comment by emar-kar** [comment]
@aprodigalson can you please check your use case with the new version?

**Comment by aprodigalson** [comment]
thanks! this issue has been fixed in the new version
