### ISSUE TITLE
Code broken

### ISSUE THREAD

**Issue by danyal-wanclouds** [bigkevmcd/go-configparser#5]
Could you please test your code again? I think it is broken. when you create a new config parser, it says undefined p, err

**Comment by danyal-wanclouds** [comment]
Sorry, the explanation of usage is wrong. Found a workaround.

**Comment by bigkevmcd** [comment]
@danyal-wanclouds I think I've improved that line in the README, if you have any further suggestions, please feel free to either open an issue, or, create a PR.
